version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: iot_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Expone el puerto para que pgAdmin local se conecte
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Persistencia de datos
    networks:
      - iot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de FastAPI (nuestra API)
  api:
    build: .
    container_name: iot_fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app  # Montaje en caliente para desarrollo
    networks:
      - iot_network

  # Servicio de Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: iot_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - iot_network

volumes:
  postgres_data:
  grafana_data:

networks:
  iot_network:
    driver: bridge
